### ISSUE TITLE
Page breaks before headers

### ISSUE THREAD

**Issue by mkerd** [SimeonLukas/obsidian-kindle-export#12]
First off, thank you for this amazing plugin and the backend. I was able to set everything up and it works like a charm.

I have a question about the headers - there's a page break before every header in my file. As a result, I have dozens of page in situations where the whole content could be just a few pages. Is this intentional? If yes, how can I customize it?

**Comment by SimeonLukas** [comment]
Hithere,

thanks for using the Plugin.
When I wrote the Plugin, it was intentional.
I thought it would be a great Idea. :-)

In the server-side index.php is a function:

```
// if text contains <h

$pages = explode('<h', $text);	
foreach ($pages as $page) {
    if ($page != '') {
        // replace <i> and <b>
        $pagewoi = preg_replace_callback('/<i>(.*?)<\/i>/', function($matches5) {
            return $matches5[1];
        }, $page);
        $headline = strpos($pagewoi, '>');
        $headline = substr($pagewoi, $headline + 1);
        $headline = substr($headline, 0, strpos($headline, '<'));
        $epub->AddPage('<h' . $page, false, $headline);
    }
}
```

which splits the pages by headlines, so I thought, this would be more readable.

Following index.php would only break by h1 tags.
[index.php](https://gist.github.com/SimeonLukas/88a92fdb620d33afeb55b8b5b3327ea2)

Just swap them.
I hope this helps.

Greetings,
Simeon
